### ISSUE TITLE
Option to request deletion of bot's data.

### ISSUE THREAD

**Issue by 3eif** [dbl-marcorennmaus-de/issues#4]
**Feature description**:
An option where users can request the deletion of their own bot's data in case it is messed up due to an issue in the past.
**Why you feel it would be a good addition**:
It'll reduce the amount of messed up statistics and graphs.
**Screenshots or Visual concept** (If applicable):
This would probably just be a button that would appear when the user is logged in and owns the bot.

**Comment by Luke-6723** [comment]
Generally with anomalies we can clear them up directly from the database for you. The only time we would be accepting of deleting bot data is if that data is no longer available from top.gg due to the fact if it's still available would just be refetched again. Which defeats the point of deleting user data.
